pos_fuel = {4361: {4051: {'quantity': 1, 'typeName': u'Nitrogen Fuel Block'},
        16275: {'quantity': 200, 'typeName': u'Strontium Clathrates'}},
 12235: {4247: {'quantity': 40, 'typeName': u'Helium Fuel Block'},
         16275: {'quantity': 400, 'typeName': u'Strontium Clathrates'},
         24592: {'quantity': 1, 'typeName': u'Amarr Empire Starbase Charter'},
         24593: {'quantity': 1,
                 'typeName': u'Caldari State Starbase Charter'},
         24594: {'quantity': 1,
                 'typeName': u'Gallente Federation Starbase Charter'},
         24595: {'quantity': 1,
                 'typeName': u'Minmatar Republic Starbase Charter'},
         24596: {'quantity': 1,
                 'typeName': u'Khanid Kingdom Starbase Charter'},
         24597: {'quantity': 1,
                 'typeName': u'Ammatar Mandate Starbase Charter'}},
 12236: {4312: {'quantity': 40, 'typeName': u'Oxygen Fuel Block'},
         16275: {'quantity': 400, 'typeName': u'Strontium Clathrates'},
         24592: {'quantity': 1, 'typeName': u'Amarr Empire Starbase Charter'},
         24593: {'quantity': 1,
                 'typeName': u'Caldari State Starbase Charter'},
         24594: {'quantity': 1,
                 'typeName': u'Gallente Federation Starbase Charter'},
         24595: {'quantity': 1,
                 'typeName': u'Minmatar Republic Starbase Charter'},
         24596: {'quantity': 1,
                 'typeName': u'Khanid Kingdom Starbase Charter'},
         24597: {'quantity': 1,
                 'typeName': u'Ammatar Mandate Starbase Charter'}},
 16213: {4051: {'quantity': 40, 'typeName': u'Nitrogen Fuel Block'},
         16275: {'quantity': 400, 'typeName': u'Strontium Clathrates'},
         24592: {'quantity': 1, 'typeName': u'Amarr Empire Starbase Charter'},
         24593: {'quantity': 1,
                 'typeName': u'Caldari State Starbase Charter'},
         24594: {'quantity': 1,
                 'typeName': u'Gallente Federation Starbase Charter'},
         24595: {'quantity': 1,
                 'typeName': u'Minmatar Republic Starbase Charter'},
         24596: {'quantity': 1,
                 'typeName': u'Khanid Kingdom Starbase Charter'},
         24597: {'quantity': 1,
                 'typeName': u'Ammatar Mandate Starbase Charter'}},
 16214: {4246: {'quantity': 40, 'typeName': u'Hydrogen Fuel Block'},
         16275: {'quantity': 400, 'typeName': u'Strontium Clathrates'},
         24592: {'quantity': 1, 'typeName': u'Amarr Empire Starbase Charter'},
         24593: {'quantity': 1,
                 'typeName': u'Caldari State Starbase Charter'},
         24594: {'quantity': 1,
                 'typeName': u'Gallente Federation Starbase Charter'},
         24595: {'quantity': 1,
                 'typeName': u'Minmatar Republic Starbase Charter'},
         24596: {'quantity': 1,
                 'typeName': u'Khanid Kingdom Starbase Charter'},
         24597: {'quantity': 1,
                 'typeName': u'Ammatar Mandate Starbase Charter'}},
 16286: {16275: {'quantity': 200, 'typeName': u'Strontium Clathrates'}},
 20059: {4247: {'quantity': 20, 'typeName': u'Helium Fuel Block'},
         16275: {'quantity': 200, 'typeName': u'Strontium Clathrates'},
         24592: {'quantity': 1, 'typeName': u'Amarr Empire Starbase Charter'},
         24593: {'quantity': 1,
                 'typeName': u'Caldari State Starbase Charter'},
         24594: {'quantity': 1,
                 'typeName': u'Gallente Federation Starbase Charter'},
         24595: {'quantity': 1,
                 'typeName': u'Minmatar Republic Starbase Charter'},
         24596: {'quantity': 1,
                 'typeName': u'Khanid Kingdom Starbase Charter'},
         24597: {'quantity': 1,
                 'typeName': u'Ammatar Mandate Starbase Charter'}},
 20060: {4247: {'quantity': 10, 'typeName': u'Helium Fuel Block'},
         16275: {'quantity': 100, 'typeName': u'Strontium Clathrates'},
         24592: {'quantity': 1, 'typeName': u'Amarr Empire Starbase Charter'},
         24593: {'quantity': 1,
                 'typeName': u'Caldari State Starbase Charter'},
         24594: {'quantity': 1,
                 'typeName': u'Gallente Federation Starbase Charter'},
         24595: {'quantity': 1,
                 'typeName': u'Minmatar Republic Starbase Charter'},
         24596: {'quantity': 1,
                 'typeName': u'Khanid Kingdom Starbase Charter'},
         24597: {'quantity': 1,
                 'typeName': u'Ammatar Mandate Starbase Charter'}},
 20061: {4051: {'quantity': 20, 'typeName': u'Nitrogen Fuel Block'},
         16275: {'quantity': 200, 'typeName': u'Strontium Clathrates'},
         24592: {'quantity': 1, 'typeName': u'Amarr Empire Starbase Charter'},
         24593: {'quantity': 1,
                 'typeName': u'Caldari State Starbase Charter'},
         24594: {'quantity': 1,
                 'typeName': u'Gallente Federation Starbase Charter'},
         24595: {'quantity': 1,
                 'typeName': u'Minmatar Republic Starbase Charter'},
         24596: {'quantity': 1,
                 'typeName': u'Khanid Kingdom Starbase Charter'},
         24597: {'quantity': 1,
                 'typeName': u'Ammatar Mandate Starbase Charter'}},
 20062: {4051: {'quantity': 10, 'typeName': u'Nitrogen Fuel Block'},
         16275: {'quantity': 100, 'typeName': u'Strontium Clathrates'},
         24592: {'quantity': 1, 'typeName': u'Amarr Empire Starbase Charter'},
         24593: {'quantity': 1,
                 'typeName': u'Caldari State Starbase Charter'},
         24594: {'quantity': 1,
                 'typeName': u'Gallente Federation Starbase Charter'},
         24595: {'quantity': 1,
                 'typeName': u'Minmatar Republic Starbase Charter'},
         24596: {'quantity': 1,
                 'typeName': u'Khanid Kingdom Starbase Charter'},
         24597: {'quantity': 1,
                 'typeName': u'Ammatar Mandate Starbase Charter'}},
 20063: {4312: {'quantity': 20, 'typeName': u'Oxygen Fuel Block'},
         16275: {'quantity': 200, 'typeName': u'Strontium Clathrates'},
         24592: {'quantity': 1, 'typeName': u'Amarr Empire Starbase Charter'},
         24593: {'quantity': 1,
                 'typeName': u'Caldari State Starbase Charter'},
         24594: {'quantity': 1,
                 'typeName': u'Gallente Federation Starbase Charter'},
         24595: {'quantity': 1,
                 'typeName': u'Minmatar Republic Starbase Charter'},
         24596: {'quantity': 1,
                 'typeName': u'Khanid Kingdom Starbase Charter'},
         24597: {'quantity': 1,
                 'typeName': u'Ammatar Mandate Starbase Charter'}},
 20064: {4312: {'quantity': 10, 'typeName': u'Oxygen Fuel Block'},
         16275: {'quantity': 100, 'typeName': u'Strontium Clathrates'},
         24592: {'quantity': 1, 'typeName': u'Amarr Empire Starbase Charter'},
         24593: {'quantity': 1,
                 'typeName': u'Caldari State Starbase Charter'},
         24594: {'quantity': 1,
                 'typeName': u'Gallente Federation Starbase Charter'},
         24595: {'quantity': 1,
                 'typeName': u'Minmatar Republic Starbase Charter'},
         24596: {'quantity': 1,
                 'typeName': u'Khanid Kingdom Starbase Charter'},
         24597: {'quantity': 1,
                 'typeName': u'Ammatar Mandate Starbase Charter'}},
 20065: {4246: {'quantity': 20, 'typeName': u'Hydrogen Fuel Block'},
         16275: {'quantity': 200, 'typeName': u'Strontium Clathrates'},
         24592: {'quantity': 1, 'typeName': u'Amarr Empire Starbase Charter'},
         24593: {'quantity': 1,
                 'typeName': u'Caldari State Starbase Charter'},
         24594: {'quantity': 1,
                 'typeName': u'Gallente Federation Starbase Charter'},
         24595: {'quantity': 1,
                 'typeName': u'Minmatar Republic Starbase Charter'},
         24596: {'quantity': 1,
                 'typeName': u'Khanid Kingdom Starbase Charter'},
         24597: {'quantity': 1,
                 'typeName': u'Ammatar Mandate Starbase Charter'}},
 20066: {4246: {'quantity': 10, 'typeName': u'Hydrogen Fuel Block'},
         16275: {'quantity': 100, 'typeName': u'Strontium Clathrates'},
         24592: {'quantity': 1, 'typeName': u'Amarr Empire Starbase Charter'},
         24593: {'quantity': 1,
                 'typeName': u'Caldari State Starbase Charter'},
         24594: {'quantity': 1,
                 'typeName': u'Gallente Federation Starbase Charter'},
         24595: {'quantity': 1,
                 'typeName': u'Minmatar Republic Starbase Charter'},
         24596: {'quantity': 1,
                 'typeName': u'Khanid Kingdom Starbase Charter'},
         24597: {'quantity': 1,
                 'typeName': u'Ammatar Mandate Starbase Charter'}},
 27530: {4247: {'quantity': 36, 'typeName': u'Helium Fuel Block'},
         16275: {'quantity': 400, 'typeName': u'Strontium Clathrates'},
         24592: {'quantity': 1, 'typeName': u'Amarr Empire Starbase Charter'},
         24593: {'quantity': 1,
                 'typeName': u'Caldari State Starbase Charter'},
         24594: {'quantity': 1,
                 'typeName': u'Gallente Federation Starbase Charter'},
         24595: {'quantity': 1,
                 'typeName': u'Minmatar Republic Starbase Charter'},
         24596: {'quantity': 1,
                 'typeName': u'Khanid Kingdom Starbase Charter'},
         24597: {'quantity': 1,
                 'typeName': u'Ammatar Mandate Starbase Charter'}},
 27532: {4247: {'quantity': 32, 'typeName': u'Helium Fuel Block'},
         16275: {'quantity': 400, 'typeName': u'Strontium Clathrates'},
         24592: {'quantity': 1, 'typeName': u'Amarr Empire Starbase Charter'},
         24593: {'quantity': 1,
                 'typeName': u'Caldari State Starbase Charter'},
         24594: {'quantity': 1,
                 'typeName': u'Gallente Federation Starbase Charter'},
         24595: {'quantity': 1,
                 'typeName': u'Minmatar Republic Starbase Charter'},
         24596: {'quantity': 1,
                 'typeName': u'Khanid Kingdom Starbase Charter'},
         24597: {'quantity': 1,
                 'typeName': u'Ammatar Mandate Starbase Charter'}},
 27533: {4051: {'quantity': 36, 'typeName': u'Nitrogen Fuel Block'},
         16275: {'quantity': 400, 'typeName': u'Strontium Clathrates'},
         24592: {'quantity': 1, 'typeName': u'Amarr Empire Starbase Charter'},
         24593: {'quantity': 1,
                 'typeName': u'Caldari State Starbase Charter'},
         24594: {'quantity': 1,
                 'typeName': u'Gallente Federation Starbase Charter'},
         24595: {'quantity': 1,
                 'typeName': u'Minmatar Republic Starbase Charter'},
         24596: {'quantity': 1,
                 'typeName': u'Khanid Kingdom Starbase Charter'},
         24597: {'quantity': 1,
                 'typeName': u'Ammatar Mandate Starbase Charter'}},
 27535: {4051: {'quantity': 32, 'typeName': u'Nitrogen Fuel Block'},
         16275: {'quantity': 400, 'typeName': u'Strontium Clathrates'},
         24592: {'quantity': 1, 'typeName': u'Amarr Empire Starbase Charter'},
         24593: {'quantity': 1,
                 'typeName': u'Caldari State Starbase Charter'},
         24594: {'quantity': 1,
                 'typeName': u'Gallente Federation Starbase Charter'},
         24595: {'quantity': 1,
                 'typeName': u'Minmatar Republic Starbase Charter'},
         24596: {'quantity': 1,
                 'typeName': u'Khanid Kingdom Starbase Charter'},
         24597: {'quantity': 1,
                 'typeName': u'Ammatar Mandate Starbase Charter'}},
 27536: {4312: {'quantity': 36, 'typeName': u'Oxygen Fuel Block'},
         16275: {'quantity': 400, 'typeName': u'Strontium Clathrates'},
         24592: {'quantity': 1, 'typeName': u'Amarr Empire Starbase Charter'},
         24593: {'quantity': 1,
                 'typeName': u'Caldari State Starbase Charter'},
         24594: {'quantity': 1,
                 'typeName': u'Gallente Federation Starbase Charter'},
         24595: {'quantity': 1,
                 'typeName': u'Minmatar Republic Starbase Charter'},
         24596: {'quantity': 1,
                 'typeName': u'Khanid Kingdom Starbase Charter'},
         24597: {'quantity': 1,
                 'typeName': u'Ammatar Mandate Starbase Charter'}},
 27538: {4312: {'quantity': 32, 'typeName': u'Oxygen Fuel Block'},
         16275: {'quantity': 400, 'typeName': u'Strontium Clathrates'},
         24592: {'quantity': 1, 'typeName': u'Amarr Empire Starbase Charter'},
         24593: {'quantity': 1,
                 'typeName': u'Caldari State Starbase Charter'},
         24594: {'quantity': 1,
                 'typeName': u'Gallente Federation Starbase Charter'},
         24595: {'quantity': 1,
                 'typeName': u'Minmatar Republic Starbase Charter'},
         24596: {'quantity': 1,
                 'typeName': u'Khanid Kingdom Starbase Charter'},
         24597: {'quantity': 1,
                 'typeName': u'Ammatar Mandate Starbase Charter'}},
 27539: {4246: {'quantity': 36, 'typeName': u'Hydrogen Fuel Block'},
         16275: {'quantity': 400, 'typeName': u'Strontium Clathrates'},
         24592: {'quantity': 1, 'typeName': u'Amarr Empire Starbase Charter'},
         24593: {'quantity': 1,
                 'typeName': u'Caldari State Starbase Charter'},
         24594: {'quantity': 1,
                 'typeName': u'Gallente Federation Starbase Charter'},
         24595: {'quantity': 1,
                 'typeName': u'Minmatar Republic Starbase Charter'},
         24596: {'quantity': 1,
                 'typeName': u'Khanid Kingdom Starbase Charter'},
         24597: {'quantity': 1,
                 'typeName': u'Ammatar Mandate Starbase Charter'}},
 27540: {4246: {'quantity': 32, 'typeName': u'Hydrogen Fuel Block'},
         16275: {'quantity': 400, 'typeName': u'Strontium Clathrates'},
         24592: {'quantity': 1, 'typeName': u'Amarr Empire Starbase Charter'},
         24593: {'quantity': 1,
                 'typeName': u'Caldari State Starbase Charter'},
         24594: {'quantity': 1,
                 'typeName': u'Gallente Federation Starbase Charter'},
         24595: {'quantity': 1,
                 'typeName': u'Minmatar Republic Starbase Charter'},
         24596: {'quantity': 1,
                 'typeName': u'Khanid Kingdom Starbase Charter'},
         24597: {'quantity': 1,
                 'typeName': u'Ammatar Mandate Starbase Charter'}},
 27589: {4247: {'quantity': 18, 'typeName': u'Helium Fuel Block'},
         16275: {'quantity': 200, 'typeName': u'Strontium Clathrates'},
         24592: {'quantity': 1, 'typeName': u'Amarr Empire Starbase Charter'},
         24593: {'quantity': 1,
                 'typeName': u'Caldari State Starbase Charter'},
         24594: {'quantity': 1,
                 'typeName': u'Gallente Federation Starbase Charter'},
         24595: {'quantity': 1,
                 'typeName': u'Minmatar Republic Starbase Charter'},
         24596: {'quantity': 1,
                 'typeName': u'Khanid Kingdom Starbase Charter'},
         24597: {'quantity': 1,
                 'typeName': u'Ammatar Mandate Starbase Charter'}},
 27591: {4247: {'quantity': 16, 'typeName': u'Helium Fuel Block'},
         16275: {'quantity': 200, 'typeName': u'Strontium Clathrates'},
         24592: {'quantity': 1, 'typeName': u'Amarr Empire Starbase Charter'},
         24593: {'quantity': 1,
                 'typeName': u'Caldari State Starbase Charter'},
         24594: {'quantity': 1,
                 'typeName': u'Gallente Federation Starbase Charter'},
         24595: {'quantity': 1,
                 'typeName': u'Minmatar Republic Starbase Charter'},
         24596: {'quantity': 1,
                 'typeName': u'Khanid Kingdom Starbase Charter'},
         24597: {'quantity': 1,
                 'typeName': u'Ammatar Mandate Starbase Charter'}},
 27592: {4247: {'quantity': 9, 'typeName': u'Helium Fuel Block'},
         16275: {'quantity': 100, 'typeName': u'Strontium Clathrates'},
         24592: {'quantity': 1, 'typeName': u'Amarr Empire Starbase Charter'},
         24593: {'quantity': 1,
                 'typeName': u'Caldari State Starbase Charter'},
         24594: {'quantity': 1,
                 'typeName': u'Gallente Federation Starbase Charter'},
         24595: {'quantity': 1,
                 'typeName': u'Minmatar Republic Starbase Charter'},
         24596: {'quantity': 1,
                 'typeName': u'Khanid Kingdom Starbase Charter'},
         24597: {'quantity': 1,
                 'typeName': u'Ammatar Mandate Starbase Charter'}},
 27594: {4247: {'quantity': 8, 'typeName': u'Helium Fuel Block'},
         16275: {'quantity': 100, 'typeName': u'Strontium Clathrates'},
         24592: {'quantity': 1, 'typeName': u'Amarr Empire Starbase Charter'},
         24593: {'quantity': 1,
                 'typeName': u'Caldari State Starbase Charter'},
         24594: {'quantity': 1,
                 'typeName': u'Gallente Federation Starbase Charter'},
         24595: {'quantity': 1,
                 'typeName': u'Minmatar Republic Starbase Charter'},
         24596: {'quantity': 1,
                 'typeName': u'Khanid Kingdom Starbase Charter'},
         24597: {'quantity': 1,
                 'typeName': u'Ammatar Mandate Starbase Charter'}},
 27595: {4051: {'quantity': 18, 'typeName': u'Nitrogen Fuel Block'},
         16275: {'quantity': 200, 'typeName': u'Strontium Clathrates'},
         24592: {'quantity': 1, 'typeName': u'Amarr Empire Starbase Charter'},
         24593: {'quantity': 1,
                 'typeName': u'Caldari State Starbase Charter'},
         24594: {'quantity': 1,
                 'typeName': u'Gallente Federation Starbase Charter'},
         24595: {'quantity': 1,
                 'typeName': u'Minmatar Republic Starbase Charter'},
         24596: {'quantity': 1,
                 'typeName': u'Khanid Kingdom Starbase Charter'},
         24597: {'quantity': 1,
                 'typeName': u'Ammatar Mandate Starbase Charter'}},
 27597: {4051: {'quantity': 16, 'typeName': u'Nitrogen Fuel Block'},
         16275: {'quantity': 200, 'typeName': u'Strontium Clathrates'},
         24592: {'quantity': 1, 'typeName': u'Amarr Empire Starbase Charter'},
         24593: {'quantity': 1,
                 'typeName': u'Caldari State Starbase Charter'},
         24594: {'quantity': 1,
                 'typeName': u'Gallente Federation Starbase Charter'},
         24595: {'quantity': 1,
                 'typeName': u'Minmatar Republic Starbase Charter'},
         24596: {'quantity': 1,
                 'typeName': u'Khanid Kingdom Starbase Charter'},
         24597: {'quantity': 1,
                 'typeName': u'Ammatar Mandate Starbase Charter'}},
 27598: {4051: {'quantity': 9, 'typeName': u'Nitrogen Fuel Block'},
         16275: {'quantity': 100, 'typeName': u'Strontium Clathrates'},
         24592: {'quantity': 1, 'typeName': u'Amarr Empire Starbase Charter'},
         24593: {'quantity': 1,
                 'typeName': u'Caldari State Starbase Charter'},
         24594: {'quantity': 1,
                 'typeName': u'Gallente Federation Starbase Charter'},
         24595: {'quantity': 1,
                 'typeName': u'Minmatar Republic Starbase Charter'},
         24596: {'quantity': 1,
                 'typeName': u'Khanid Kingdom Starbase Charter'},
         24597: {'quantity': 1,
                 'typeName': u'Ammatar Mandate Starbase Charter'}},
 27600: {4051: {'quantity': 8, 'typeName': u'Nitrogen Fuel Block'},
         16275: {'quantity': 100, 'typeName': u'Strontium Clathrates'},
         24592: {'quantity': 1, 'typeName': u'Amarr Empire Starbase Charter'},
         24593: {'quantity': 1,
                 'typeName': u'Caldari State Starbase Charter'},
         24594: {'quantity': 1,
                 'typeName': u'Gallente Federation Starbase Charter'},
         24595: {'quantity': 1,
                 'typeName': u'Minmatar Republic Starbase Charter'},
         24596: {'quantity': 1,
                 'typeName': u'Khanid Kingdom Starbase Charter'},
         24597: {'quantity': 1,
                 'typeName': u'Ammatar Mandate Starbase Charter'}},
 27601: {4312: {'quantity': 18, 'typeName': u'Oxygen Fuel Block'},
         16275: {'quantity': 200, 'typeName': u'Strontium Clathrates'},
         24592: {'quantity': 1, 'typeName': u'Amarr Empire Starbase Charter'},
         24593: {'quantity': 1,
                 'typeName': u'Caldari State Starbase Charter'},
         24594: {'quantity': 1,
                 'typeName': u'Gallente Federation Starbase Charter'},
         24595: {'quantity': 1,
                 'typeName': u'Minmatar Republic Starbase Charter'},
         24596: {'quantity': 1,
                 'typeName': u'Khanid Kingdom Starbase Charter'},
         24597: {'quantity': 1,
                 'typeName': u'Ammatar Mandate Starbase Charter'}},
 27603: {4312: {'quantity': 16, 'typeName': u'Oxygen Fuel Block'},
         16275: {'quantity': 200, 'typeName': u'Strontium Clathrates'},
         24592: {'quantity': 1, 'typeName': u'Amarr Empire Starbase Charter'},
         24593: {'quantity': 1,
                 'typeName': u'Caldari State Starbase Charter'},
         24594: {'quantity': 1,
                 'typeName': u'Gallente Federation Starbase Charter'},
         24595: {'quantity': 1,
                 'typeName': u'Minmatar Republic Starbase Charter'},
         24596: {'quantity': 1,
                 'typeName': u'Khanid Kingdom Starbase Charter'},
         24597: {'quantity': 1,
                 'typeName': u'Ammatar Mandate Starbase Charter'}},
 27604: {4312: {'quantity': 9, 'typeName': u'Oxygen Fuel Block'},
         16275: {'quantity': 100, 'typeName': u'Strontium Clathrates'},
         24592: {'quantity': 1, 'typeName': u'Amarr Empire Starbase Charter'},
         24593: {'quantity': 1,
                 'typeName': u'Caldari State Starbase Charter'},
         24594: {'quantity': 1,
                 'typeName': u'Gallente Federation Starbase Charter'},
         24595: {'quantity': 1,
                 'typeName': u'Minmatar Republic Starbase Charter'},
         24596: {'quantity': 1,
                 'typeName': u'Khanid Kingdom Starbase Charter'},
         24597: {'quantity': 1,
                 'typeName': u'Ammatar Mandate Starbase Charter'}},
 27606: {4312: {'quantity': 8, 'typeName': u'Oxygen Fuel Block'},
         16275: {'quantity': 100, 'typeName': u'Strontium Clathrates'},
         24592: {'quantity': 1, 'typeName': u'Amarr Empire Starbase Charter'},
         24593: {'quantity': 1,
                 'typeName': u'Caldari State Starbase Charter'},
         24594: {'quantity': 1,
                 'typeName': u'Gallente Federation Starbase Charter'},
         24595: {'quantity': 1,
                 'typeName': u'Minmatar Republic Starbase Charter'},
         24596: {'quantity': 1,
                 'typeName': u'Khanid Kingdom Starbase Charter'},
         24597: {'quantity': 1,
                 'typeName': u'Ammatar Mandate Starbase Charter'}},
 27607: {4246: {'quantity': 18, 'typeName': u'Hydrogen Fuel Block'},
         16275: {'quantity': 200, 'typeName': u'Strontium Clathrates'},
         24592: {'quantity': 1, 'typeName': u'Amarr Empire Starbase Charter'},
         24593: {'quantity': 1,
                 'typeName': u'Caldari State Starbase Charter'},
         24594: {'quantity': 1,
                 'typeName': u'Gallente Federation Starbase Charter'},
         24595: {'quantity': 1,
                 'typeName': u'Minmatar Republic Starbase Charter'},
         24596: {'quantity': 1,
                 'typeName': u'Khanid Kingdom Starbase Charter'},
         24597: {'quantity': 1,
                 'typeName': u'Ammatar Mandate Starbase Charter'}},
 27609: {4246: {'quantity': 16, 'typeName': u'Hydrogen Fuel Block'},
         16275: {'quantity': 200, 'typeName': u'Strontium Clathrates'},
         24592: {'quantity': 1, 'typeName': u'Amarr Empire Starbase Charter'},
         24593: {'quantity': 1,
                 'typeName': u'Caldari State Starbase Charter'},
         24594: {'quantity': 1,
                 'typeName': u'Gallente Federation Starbase Charter'},
         24595: {'quantity': 1,
                 'typeName': u'Minmatar Republic Starbase Charter'},
         24596: {'quantity': 1,
                 'typeName': u'Khanid Kingdom Starbase Charter'},
         24597: {'quantity': 1,
                 'typeName': u'Ammatar Mandate Starbase Charter'}},
 27610: {4246: {'quantity': 9, 'typeName': u'Hydrogen Fuel Block'},
         16275: {'quantity': 100, 'typeName': u'Strontium Clathrates'},
         24592: {'quantity': 1, 'typeName': u'Amarr Empire Starbase Charter'},
         24593: {'quantity': 1,
                 'typeName': u'Caldari State Starbase Charter'},
         24594: {'quantity': 1,
                 'typeName': u'Gallente Federation Starbase Charter'},
         24595: {'quantity': 1,
                 'typeName': u'Minmatar Republic Starbase Charter'},
         24596: {'quantity': 1,
                 'typeName': u'Khanid Kingdom Starbase Charter'},
         24597: {'quantity': 1,
                 'typeName': u'Ammatar Mandate Starbase Charter'}},
 27612: {4246: {'quantity': 8, 'typeName': u'Hydrogen Fuel Block'},
         16275: {'quantity': 100, 'typeName': u'Strontium Clathrates'},
         24592: {'quantity': 1, 'typeName': u'Amarr Empire Starbase Charter'},
         24593: {'quantity': 1,
                 'typeName': u'Caldari State Starbase Charter'},
         24594: {'quantity': 1,
                 'typeName': u'Gallente Federation Starbase Charter'},
         24595: {'quantity': 1,
                 'typeName': u'Minmatar Republic Starbase Charter'},
         24596: {'quantity': 1,
                 'typeName': u'Khanid Kingdom Starbase Charter'},
         24597: {'quantity': 1,
                 'typeName': u'Ammatar Mandate Starbase Charter'}},
 27780: {4247: {'quantity': 36, 'typeName': u'Helium Fuel Block'},
         16275: {'quantity': 400, 'typeName': u'Strontium Clathrates'},
         24592: {'quantity': 1, 'typeName': u'Amarr Empire Starbase Charter'},
         24593: {'quantity': 1,
                 'typeName': u'Caldari State Starbase Charter'},
         24594: {'quantity': 1,
                 'typeName': u'Gallente Federation Starbase Charter'},
         24595: {'quantity': 1,
                 'typeName': u'Minmatar Republic Starbase Charter'},
         24596: {'quantity': 1,
                 'typeName': u'Khanid Kingdom Starbase Charter'},
         24597: {'quantity': 1,
                 'typeName': u'Ammatar Mandate Starbase Charter'}},
 27782: {4247: {'quantity': 18, 'typeName': u'Helium Fuel Block'},
         16275: {'quantity': 200, 'typeName': u'Strontium Clathrates'},
         24592: {'quantity': 1, 'typeName': u'Amarr Empire Starbase Charter'},
         24593: {'quantity': 1,
                 'typeName': u'Caldari State Starbase Charter'},
         24594: {'quantity': 1,
                 'typeName': u'Gallente Federation Starbase Charter'},
         24595: {'quantity': 1,
                 'typeName': u'Minmatar Republic Starbase Charter'},
         24596: {'quantity': 1,
                 'typeName': u'Khanid Kingdom Starbase Charter'},
         24597: {'quantity': 1,
                 'typeName': u'Ammatar Mandate Starbase Charter'}},
 27784: {4247: {'quantity': 9, 'typeName': u'Helium Fuel Block'},
         16275: {'quantity': 100, 'typeName': u'Strontium Clathrates'},
         24592: {'quantity': 1, 'typeName': u'Amarr Empire Starbase Charter'},
         24593: {'quantity': 1,
                 'typeName': u'Caldari State Starbase Charter'},
         24594: {'quantity': 1,
                 'typeName': u'Gallente Federation Starbase Charter'},
         24595: {'quantity': 1,
                 'typeName': u'Minmatar Republic Starbase Charter'},
         24596: {'quantity': 1,
                 'typeName': u'Khanid Kingdom Starbase Charter'},
         24597: {'quantity': 1,
                 'typeName': u'Ammatar Mandate Starbase Charter'}},
 27786: {4247: {'quantity': 32, 'typeName': u'Helium Fuel Block'},
         16275: {'quantity': 400, 'typeName': u'Strontium Clathrates'},
         24592: {'quantity': 1, 'typeName': u'Amarr Empire Starbase Charter'},
         24593: {'quantity': 1,
                 'typeName': u'Caldari State Starbase Charter'},
         24594: {'quantity': 1,
                 'typeName': u'Gallente Federation Starbase Charter'},
         24595: {'quantity': 1,
                 'typeName': u'Minmatar Republic Starbase Charter'},
         24596: {'quantity': 1,
                 'typeName': u'Khanid Kingdom Starbase Charter'},
         24597: {'quantity': 1,
                 'typeName': u'Ammatar Mandate Starbase Charter'}},
 27788: {4247: {'quantity': 16, 'typeName': u'Helium Fuel Block'},
         16275: {'quantity': 200, 'typeName': u'Strontium Clathrates'},
         24592: {'quantity': 1, 'typeName': u'Amarr Empire Starbase Charter'},
         24593: {'quantity': 1,
                 'typeName': u'Caldari State Starbase Charter'},
         24594: {'quantity': 1,
                 'typeName': u'Gallente Federation Starbase Charter'},
         24595: {'quantity': 1,
                 'typeName': u'Minmatar Republic Starbase Charter'},
         24596: {'quantity': 1,
                 'typeName': u'Khanid Kingdom Starbase Charter'},
         24597: {'quantity': 1,
                 'typeName': u'Ammatar Mandate Starbase Charter'}},
 27790: {4247: {'quantity': 8, 'typeName': u'Helium Fuel Block'},
         16275: {'quantity': 100, 'typeName': u'Strontium Clathrates'},
         24592: {'quantity': 1, 'typeName': u'Amarr Empire Starbase Charter'},
         24593: {'quantity': 1,
                 'typeName': u'Caldari State Starbase Charter'},
         24594: {'quantity': 1,
                 'typeName': u'Gallente Federation Starbase Charter'},
         24595: {'quantity': 1,
                 'typeName': u'Minmatar Republic Starbase Charter'},
         24596: {'quantity': 1,
                 'typeName': u'Khanid Kingdom Starbase Charter'},
         24597: {'quantity': 1,
                 'typeName': u'Ammatar Mandate Starbase Charter'}}}

moon_goo = {16633: {'typeName': u'Hydrocarbons', 'volume': 0.1},
 16634: {'typeName': u'Atmospheric Gases', 'volume': 0.1},
 16635: {'typeName': u'Evaporite Deposits', 'volume': 0.1},
 16636: {'typeName': u'Silicates', 'volume': 0.1},
 16637: {'typeName': u'Tungsten', 'volume': 0.4},
 16638: {'typeName': u'Titanium', 'volume': 0.4},
 16639: {'typeName': u'Scandium', 'volume': 0.4},
 16640: {'typeName': u'Cobalt', 'volume': 0.4},
 16641: {'typeName': u'Chromium', 'volume': 0.6},
 16642: {'typeName': u'Vanadium', 'volume': 1.0},
 16643: {'typeName': u'Cadmium', 'volume': 0.4},
 16644: {'typeName': u'Platinum', 'volume': 1.0},
 16646: {'typeName': u'Mercury', 'volume': 0.8},
 16647: {'typeName': u'Caesium', 'volume': 0.8},
 16648: {'typeName': u'Hafnium', 'volume': 0.8},
 16649: {'typeName': u'Technetium', 'volume': 0.8},
 16650: {'typeName': u'Dysprosium', 'volume': 1.0},
 16651: {'typeName': u'Neodymium', 'volume': 1.0},
 16652: {'typeName': u'Promethium', 'volume': 1.0},
 16653: {'typeName': u'Thulium', 'volume': 1.0}}